In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats

In [5]:
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4])

In [7]:
c = a - b 
c

array([10, 10, 10, 10])

In [9]:
series = pd.Series(3,index=['a','b','c'])
series

a    3
b    3
c    3
dtype: int64

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])